[package]
name = "html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkjet = "0.10"
v_htmlescape = "0.15"

[profiles.dev.package.inkjet]
opt-level = 3
